---
- hosts: remote
  vars:
    target_file: /tmp/condition_file
  tasks:
    - name: Gather file info
      stat: 
        path: "{{ target_file }}"
      register: targetfile

    - name: rename file when present
      command: mv "{{ target_file }}" /tmp/condition_file_renamed
      when: targetfile.stat.exists 
      # targetfile['stat']'xists#'] also works
