---
- hosts: remote
  become: yes
  tasks:
    - name: Stop nginx service before uninstall
      service:
        name: nginx
        state: stopped      
    - name: Uninstall nginx
      yum:
        name: nginx
        state: absent
