---
- name: Add PPS OpenJDK builds repository
  ansible.builtin.apt_repository:
    repo: ppa:openjdk-r/ppa

- name: Run apt-get update
  apt:
    update_cache: yes

- name: Install OpenJDK 11
  package:
    name: openjdk-11-jdk
    state: present


- name: Find OpenJDK 11 installled path in /usr/lib/jvm/
  find:
    paths: /usr/lib/jvm/
    recurse: no
    file_type: directory
    use_regex: yes
    patterns: 'java-11-openjdk'
  register: java_home

- debug:
    msg: "{{ java_home.files[0].path }}"

- name: create file to set JAVA_HOME environment variable
  lineinfile:
    path: /etc/profile.d/java-home.sh
    create: yes
    line: "{{ item }}" 
  with_items:
    - 'export JAVA_HOME={{ java_home.files[0].path }}'
    - 'export PATH=$PATH:$JAVA_HOME/bin'
