---
- name: Install yum-utils
  package:
    name: yum-utils
    state: present

- name: Add Hashicorp repository
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install hasicorp terraform
  package:
    name: terraform
    state: present
