---
- name: Stop and disable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: stopped
    enabled: no
  when: ansible_service_mgr == "systemd"
  failed_when: "unused_disable|failed and ('find' not in unused_disable.msg and 'found' not in unused_disable.msg)"

- name: remove user "tomcat"
  user:
    name: tomcat
    state: absent

- name: remove group "tomcat"
  group:
    name: tomcat
    state: absent

- name: remove apache-tomcat-10.0.5 related file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/apache-tomcat-10.0.5.zip
    - /opt/apache-tomcat-10.0.5  
    - /usr/share/tomcat
    - /etc/systemd/system/tomcat.service
