---
- name: Stop and disable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: stopped
    enabled: no
  when: ansible_service_mgr == "systemd"

- name: remove user "tomcat"
  user:
    name: tomcat
    state: absent

- name: remove group "tomcat"
  group:
    name: tomcat
    state: absent

- name: remove apache-tomcat-8.5.X related file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/apache-tomcat-8.5.65.zip
    - /opt/apache-tomcat-8.5.65  
    - /usr/share/tomcat
    - /etc/systemd/system/tomcat.service
