---
# tasks file for /jaga/ansible/roles/web

- name: Install httpd
  yum:
    name: httpd
    state: latest

- name: Deploy httpd conf 
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/httpd.conf
  notify: httpd service handler
