---
- name: Run apt-get update
  apt:
    update_cache: yes
    state: present

- name: Install Common packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - unzip
